### ISSUE TITLE
Regex search over malformed command crashes main thread

### ISSUE THREAD

**Issue by jcmoyer** [Sulter/MASTERlinker#15]
Possibility 1:

```
Traceback (most recent call last):
  File "./ircbot2.py", line 200, in <module>
    ircbot.main()
  File "./ircbot2.py", line 193, in main
    self.parse_command(parsed_command)
  File "./ircbot2.py", line 96, in parse_command
    channel = self.get_channel(params, nick)
  File "./ircbot2.py", line 140, in get_channel
    channel = re.search(r"^[\S]+", string).group()
  File "D:/msys64/mingw32/lib/python3.5\re.py", line 173, in search
    return _compile(pattern, flags).search(string)
TypeError: expected string or bytes-like object
```

Possibility 2:

```
Traceback (most recent call last):
  File "./ircbot2.py", line 204, in <module>
    ircbot.main()
  File "./ircbot2.py", line 197, in main
    self.parse_command(parsed_command)
  File "./ircbot2.py", line 95, in parse_command
    nick = self.get_nick(sender)
  File "./ircbot2.py", line 157, in get_nick
    nick = string.lstrip(":")
AttributeError: 'NoneType' object has no attribute 'lstrip'
```

It seems to be possible for a regex match object to be != None, but invalid. This seems to be due to encoding error and I'm not sure how you'd fix this. Perhaps you should try utf-decoding data before passing it to regex functions. This happens in a few places:

```python
nick = self.get_nick(sender) # sender = None
channel = self.get_channel(params, nick) # params = None
channel = re.search(r"^[\S]+", string).group() # ???
```

**Comment by jcmoyer** [comment]
Closing this since it's likely related to out-of-memory.
